### PR TITLE
[T2A2][W10-A4]Li Zihan

### PR DESCRIPTION
**Pull request by lizihan97**
Refactor & MethodAbstraction

### CODE REVIEW

**Comment by lizihan97** [comment]
Ready for review

**Comment by lizihan97** [comment]
Ready for review

**Comment by hwkchia** [comment]
@lizihan97 You seemed to have included all exercises in this one PR.  Please only do the exercises for a specific assignment on the associated and make a PR for each assignment.  It's difficult to review as everything is mashed together.

Next time please?  Accepted without review for this one...

**Comment by lizihan97** [comment]
@hwkchia the commit **HashMap+Enum+Varargs** is the original file before I did the activities for T2, each commit after **HashMap+Enum+Varargs** in this PR shows one step of T2A2. You can review my commits for T2A2 starting from **Improve boolean variable and function names**.  Sorry for the mess.

**Pull request closed without merging**
